### ISSUE TITLE
Backdrop removal lag after dismissal of the bottom sheet 

### ISSUE THREAD

**Issue by albertstill** [stipsan/react-spring-bottom-sheet#112]
Hi, on a vanilla install of the component, using the CSS in the getting started guide there seems to be a lag after the bottom sheet is dismissed before the dark overlay disappears. I can not see this issue in the demo examples however. Here is an example code sandbox showing the [issue](https://codesandbox.io/s/fancy-grass-yytl7?file=/src/App.js). Any ideas what's going on, are the demo's configured differently? 

Awesome repo keep up the work!

**Comment by albertstill** [comment]
@stipsan the docs use the same boilerplate [css](https://github.com/stipsan/react-spring-bottom-sheet/blob/main/pages/_app.tsx#L9) right, any idea why it would behave differently? different version of the component on the docs perhaps?

**Comment by stipsan** [comment]
You're using the correct CSS but it's missing the transpilation done here.

Scrolling down to the bottom on your codesandbox shows you this error:
![Screenshot 2021-03-18 at 22 50 21](https://user-images.githubusercontent.com/81981/111702389-79ee2e80-883c-11eb-973f-d299bc876c17.png)

[Here's the compiled boilerplate CSS](https://unpkg.com/browse/react-spring-bottom-sheet/dist/style.css) that is much easier to paste into projects as it'll work regardless of your CSS pipeline 😄

**Comment by albertstill** [comment]
Ah my bad @stipsan, I misread the getting started doc and thought that css file was vanilla css. I use Create React App so adding `@import "react-spring-bottom-sheet";` in a CSS file did the trick for me. Thanks for helping me out!
