### ISSUE TITLE
In Mobile the componet block click in Dropdown or Select

### ISSUE THREAD

**Issue by franmc01** [stipsan/react-spring-bottom-sheet#233]
![image](https://user-images.githubusercontent.com/50973629/190209774-f3278565-e232-4135-8ac9-4c14b8c120cc.png)

I tried select an option but it's not posible because the bottom-sheet-component disabled that

**Comment by larsmunkholm** [comment]
@francmarin98 Did you find a solution?

**Comment by franmc01** [comment]
Yeah bro

**Comment by larsmunkholm** [comment]
Can you share? I have the same issue.

**Comment by franmc01** [comment]
Yeah, I use prop :

blocking:false and scrollLocking: false

**Comment by larsmunkholm** [comment]
Thanks a lot! `blocking: false` seems to do it for me.

**Comment by franmc01** [comment]
It is correct with the first one it works, the second one is mostly in case there is an internal scroll, in certain versions of safari it gives problems.

I'm glad I helped you
