### ISSUE TITLE
How to prevent close?

### ISSUE THREAD

**Issue by ChanghyeonYoon** [stipsan/react-spring-bottom-sheet#278]
I want to disable close.
I set open value is always true.
But when i swipe down, bottom sheet will close.
How can i prevent close?

**Comment by ChanghyeonYoon** [comment]
I solved by onDismiss.
```
const onDismiss = React.useCallback(() => {
    if (!bottomSheetRef.current) return;
    bottomSheetRef.current.snapTo(0);
  }, [bottomSheetRef]);

<BottomSheet isOpen onDismiss={onDismiss}  />
```

**Comment by Stokel** [comment]
Is this still working? I tried this solution as my bottom sheet closes when scrolling too fast and I'm trying to prevent this.
