### ISSUE TITLE
CSS Vars with no values

### ISSUE THREAD

**Issue by yairhaimo** [stipsan/react-spring-bottom-sheet#31]
I copied the stylesheet into my project and tweaked it a bit.
I added the `postcss-custom-properties-fallback` plugin and set it up in my postcss config.
When I refresh the page the css vars seem to have no values.
If I add a dummy css property (see GIF) to the root's direct child and remove it the css vars suddenly have values and I see the panel.
I even tried to copy the css vars themselves from `defaults.json`.
I've experienced this on Desktop Chrome and Android Chrome but IPhone Chrome/Safari works fine. 🤷🏻 

![bottom-panel](https://user-images.githubusercontent.com/1783303/101680778-deddff80-3a69-11eb-98ba-ab9dabb50549.gif)

**Comment by stipsan** [comment]
Hmmm interesting. What if you copy the contents of the generated file into your project? https://unpkg.com/react-spring-bottom-sheet/dist/style.css

I see some weird NaN values happening on the `--rsbs-content-opacity`, which could mean an broken internal state.
Are you able to recreate it on codesandbox and send a link? And are you using HMR with React Fast Refresh? If you use Next.js then you do. react-spring have some issues with fasth refresh in v8, the version we're using here (it's [solved in v9](https://github.com/pmndrs/react-spring/commit/4b8cd966d593c20f9e4dff2bac5d24d7a8c92413)). If you're affected by that bug then reloading the page should fix it.

**Comment by yairhaimo** [comment]
I use NextJs but it replicated even when I built the app which doesn't use HMR/Fast Refresh.

I think i found the root cause. I added the following style to the stylesheet:
```css
[data-rsbs-content] > div {
	height: 100%;
}
```
When I remove it the css vars have values.
Let me know if it doesn't replicate for you and I'll keep searching.

**Comment by stipsan** [comment]
Ah ok I see the issue. It's messing up the height observer.
The spring will set the height on `[data-rsbs-content]` to ensure that even if content inside it changes the animation is stable. The resize observer is attached to the first element inside of `[data-rsbs-content]` which your selector is hitting. If you change it to `[data-rsbs-content-padding] > div` you avoid breaking any of that logic, and the sheet will detect the right max and min dimensions no matter what you put in there 😄

**Comment by yairhaimo** [comment]
Ok, makes sense!
What I'm trying to achieve is to have my content, which is styled as `height: 100%`, take the full space of the panel.
If I target `[data-rsbs-content-padding]` and set it to `height: 100%` it won't help since its parent (`[data-rsbs-content] > div`) has a small height.

```
[data-rsbs-content] <-- height 100%
 > div <-- shorty. this is blocking me
   > [data-rsbs-content-padding] <--- height 100%
      > MY CONTENT <--- height 100%
```

**Comment by stipsan** [comment]
Gotcha, to support that use case a small rewrite is needed. All measurements atm rest on the assumption that the content's height is independent and unaffected by the height of the sheet.
Sounds like what you need here is the ability to set snap points that allow content to have zero height until the sheet is set to a height.

However, if you don't have more than 1 snap point, would your use case be solved if you wrap `children` in an aspect-ratio trick, like this: https://css-tricks.com/aspect-ratio-boxes/
Then you could use `snapPoints={({minHeight}) => minHeight}` and the sheet will maintain the aspect ratio you have as the page width changes.

**Comment by yairhaimo** [comment]
Unfortunately i have more than one snap point. I solved it with some css on my part that is good enough for me (something specific for my use case). I'll keep in mind this solution for future uses.
Thanks a lot for your time and quick response!

**Comment by stipsan** [comment]
Ok glad it worked out in the end 👍
