### ISSUE TITLE
defaultSnap - snapPoints return bad value

### ISSUE THREAD

**Issue by yairhaimo** [stipsan/react-spring-bottom-sheet#32]
I set up my `BottomSheet` like this:
```jsx
<BottomSheet
  open={true}
  ref={bottomSheetRef}
  blocking={false}
  snapPoints={({ maxHeight }) => [200, maxHeight / 2, maxHeight - 150]}
  defaultSnap={({ snapPoints }) =>
    snapPoints[someComponentStateValue]
  }
>
```
The `snapPoints` in `defaultSnap` seem to have a bad value: an array with only 1 member and the value 0.

**Comment by stipsan** [comment]
It's not safe to select a value from `snapPoints` in `defaultSnap` by index. The reason for that is that  two-fold:
1. On initial render `maxHeight` might be `0`, I want to change this though so the `defaultSnap` and `snapPoints` are never called before dimension values are fetched and ready.
2. Duplicate values returned by `snapPoints` are removed, so its length isn't stable.

**Comment by yairhaimo** [comment]
Ok, I misunderstood the API. Thanks
